name: ucsc_fatotwobit
owner: iuc
description: faToTwoBit converts FASTA to the compact binary 2bit format
long_description: faToTwoBit converts FASTA to the compact binary 2bit format
homepage_url: https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/ucsc_tools/fatotwobit
type: unrestricted
categories:
  - Convert Formats
