name: bayescan
owner: iuc
description: "Detecting natural selection from population-based genetic data"
long_description: "BayeScan detects natural selection from population-based genetic data using population differentiation statistics (FST) derived from allele frequency differences across populations."
homepage_url: http://cmpg.unibe.ch/software/BayeScan/index.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/bayescan
type: unrestricted
categories:
- Sequence Analysis
