categories:
  - Proteomics
description: Wrapper for the 3D-Beacons API
homepage_url: https://www.ebi.ac.uk/pdbe/pdbe-kb/3dbeacons/
name: 3dbeacons_api
type: unrestricted
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/3dbeacons_api
long_description: |
  The 3D-Beacons Network provides unified programmatic access to experimentally determined and predicted structure models


