#!/usr/bin/env bash
python_script=$1
run_id=$2
information_type=$3
information_to_download=$4
chunk_type=$5
output_file=$6

touch $output_file

run_link=$(python $python_script --run_id $run_id)
run_link="$run_link/$information_type/$information_to_download"

if [[ $chunk_type == 'multiple_chunks' ]]; then
    echo "$run_link/chunks"
    chunk_nb=$(curl "$run_link/chunks")

    for i in $(seq "$chunk_nb"); do
        curl "$run_link/chunks/$i" | gunzip >> $output_file
    done
else
    curl "$run_link" >> $output_file
fi


