#!/usr/bin/env bash
query=$1
echo "$query"
output_file=$2
chunk_nb=$(curl "$query/chunks")

touch $output_file
for i in $(seq "$chunk_nb"); do
    curl "$query/chunks/$i" | gunzip >> $output_file
done
