categories:
- Machine Learning
description: A Machine Learning Framework for Benchmarking, Feature Selection, and Hyperparameter Optimization of Machine Learning Models for Multiomics Data
homepage_url: https://github.com/usegalaxy-eu/MultiOmicsClassification
long_description: |
 The multi-omics-classification tool  is designed for multi-omics data analysis , enabling reproducible and standardized multiclass classification across diverse biological datasets. It allows users to compare different feature sets, sampling strategies, classification models, and optional grid-search hyperparameter tuning, providing performance metrics for systematic model evaluation.
name: multi-omics-classification
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/multi-omics-classification
type: unrestricted
