name: mashtree
owner: iuc
description: Create a neighbor-joining tree from genome assemblies using Mash distances
long_description: |
  Mashtree rapidly compares genome assemblies using Mash distances and creates
  a neighbor-joining tree. This wrapper also returns the pairwise distance
  matrix used to construct the tree.
homepage_url: https://github.com/lskatz/mashtree
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/mashtree
type: unrestricted
categories:
  - Phylogenetics
