name: mags_visualization
owner: iuc
categories:
  - Metagenomics
  - Visualization
description: Visualization tools for MAG evaluation and analysis
long_description: |
  MAGs-visualization is a toolkit for generating publication-ready plots and
  dashboards for metagenome-assembled genomes (MAGs).

  Suppoerted visualization include:
  
  - completeness and contamination (CheckM/CheckM2)
  - taxonomic profiles (GTDB)
  - clustering (dRep)
  - abundance patterns (CoverM)
  - functional annotation (KEGG pathways)

  The Galaxy wrappers provide modular tools corresponding to each visualization type.
homepage_url: https://github.com/usegalaxy-eu/MAGs-visualization
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/mags_visualization
type: unrestricted
suite:
  name: "suite_mags_visualization"
  description: "A suite of MAGs-visualization tools"
  type: repository_suite_definition
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for MAGs-visualization tool: {{ tool_name }}"