categories:
  - Sequence Analysis
  - SAM
description: Remove genetic variation from BAM files to protect donor privacy
long_description: |
  BAMboozle removes genetic variation from sequencing reads stored in BAM format
  by replacing read bases with the reference genome bases, to protect the privacy
  and genetic information of donor individuals.
name: bamboozle
owner: iuc
homepage_url: https://github.com/sandberg-lab/dataprivacy
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/bamboozle
type: unrestricted