categories:
  - Convert Formats
description: Get the dbkey from a fasta entry.
name: fasta_to_dbkey
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/fasta_to_dbkey
type: unrestricted
