categories:
  - Metagenomics
description: Informed prediction and analysis of bacterial metabolic pathways and genome-scale networks
homepage_url: https://github.com/jotech/gapseq
long_description: |
  gapseq is designed to combine metabolic pathway analysis with metabolic network reconstruction and curation. Based on genomic information and databases for pathways and reactions, gapseq can be used for:
    prediction of metabolic pathways from various databases
    transporter inference
    metabolic model construction
    multi-step gap filling
name: gapseq
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/gapseq
type: unrestricted
