name: endorspy
owner: iuc
description: Calculate endogenous DNA percentage, clonality, and duplicates from samtools flagstats.
long_description: |
  EndorSpy is a tool designed for ancient DNA (aDNA) analysis. 
  It calculates critical quality metrics such as the percentage of endogenous DNA (on-target), 
  clonality (cluster factor), and duplication rates by comparing raw, 
  quality-filtered, and deduplicated samtools flagstat outputs.
homepage_url: https://github.com/aidaanva/endorS.py
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/endorspy
categories:
  - Sequence Analysis
