name: endorspy
owner: iuc
description: Calculate endogenous DNA percentage, clonality, and duplicates from samtools flagstats.
homepage_url: https://github.com/aidaanva/endorS.py
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/endorspy
categories:
  - Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the EndorSpy tool: {{ tool_name }}"