name: graphembed
owner: iuc
description: "Compute a 2D embedding of a data matrix given supervised class information"
long_description: "GraphEmbed computes a 2D embedding of a data matrix given supervised class information. It uses graph-based dimensionality reduction to visualize high-dimensional data in two dimensions."
homepage_url: https://github.com/fabriziocosta/GraphEmbed
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/graphembed
type: unrestricted
categories:
- Statistics
- Graphics
