auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
categories:
  - Single Cell
  - Transcriptomics
  - Visualization
homepage_url: https://bioconductor.org/packages/scater/
long_description: |
  scater provides a collection of tools for doing various analyses of
  single-cell RNA-seq gene expression data, with a focus on quality
  control and visualization.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/scater-1.38.0
suite:
  name: "suite_scater"
  description: 'Scater, Single-Cell Analysis Toolkit for Gene Expression Data in R'
type: unrestricted
