name: ucsc_gff3togenepred
owner: iuc
description: gff3ToGenePred converts a GFF3 gene annotation to genePred
long_description: gff3ToGenePred converts a GFF3 gene annotation to genePred
homepage_url: https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/ucsc_tools/gff3togenepred
type: unrestricted
categories:
  - Convert Formats
