name: mge_cluster
owner: iuc
description: Cluster mobile genetic elements and create reusable typing models
long_description: |
  mge-cluster groups mobile genetic elements using unitig presence/absence,
  dimensionality reduction, and density-based clustering. This Galaxy wrapper
  creates a new mge-cluster model from FASTA sequences.
homepage_url: https://gitlab.com/sirarredondo/mge-cluster
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/mge_cluster
type: unrestricted
categories:
  - Sequence Analysis
