name: genrich
owner: iuc
description: Genrich is a peak-caller for genomic enrichment assays (e.g. ChIP-seq, ATAC-seq).
long_description: Genrich is a peak-caller for genomic enrichment assays (e.g. ChIP-seq, ATAC-seq). It calls peaks from SAM files of reads aligned by a sequencer, supporting PCR duplicate removal, multiple replicates, and multiple modes of operation.
homepage_url: https://github.com/jsh58/Genrich
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/genrich
type: unrestricted
categories:
  - ChIP-seq
