name: mgnify_pipelines_toolkit
owner: iuc
description: Utilities for use in the MGnify pipelines
homepage_url: https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit
long_description: |
  The MGnify Pipelines Toolkit provides a collection of utilities used in the
  MGnify metagenomics and amplicon analysis workflows developed at EMBL-EBI.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/mgnify_pipelines_toolkit
type: unrestricted
categories:
- Metagenomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the mgnify-pipelines-toolkit: {{ tool_name }}"
suite:
  name: "suite_mgnify_pipelines_toolkit"
  description: Utilities for use in the MGnify pipelines
  long_description: |
    The MGnify Pipelines Toolkit provides a collection of utilities used in the
    MGnify metagenomics and amplicon analysis workflows developed at EMBL-EBI.