name: adapter_removal
owner: iuc
description: Removes residual adapter sequences from single-end (SE) or paired-end (PE) FASTQ reads.
long_description: |
  Removes residual adapter sequences from single-end (SE) or paired-end (PE) FASTQ reads, optionally trimming
  poly-X tails and low quality bases and/or merging overlapping paired-end mates into one read. Low quality reads
  are filtered based on the resulting length, the number of ambigious nucleotides ('N') present following
  trimming, the mean quality score and the sequence complexity. Adapter sequences are determined automatically
  from the input data by default, but may also be specified manually.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/adapter_removal
homepage_url: https://github.com/MikkelSchubert/adapterremoval
categories: 
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
