categories:
  - Sequence Analysis
description: Collapse walk-preserving shared affixes in a variation graph
homepage_url: https://github.com/marschall-lab/GFAffix
long_description: |
  GFAffix identifies and collapses walk-preserving shared affixes in variation graphs.
  It takes a GFA1 file as input and produces a refined GFA1 where shared prefixes
  and suffixes across walks are collapsed without changing the underlying sequences.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/gfaffix
type: unrestricted
