name: data_manager_samestr
owner: iuc
type: unrestricted
description: Strain-level analysis and comparison of metagenomic samples
long_description: |
  SameStr is a tool for identifying shared microbial strains across metagenomic
  samples using clade-specific markers from MetaPhlAn or mOTUs.
  This is the Data Manager for building SameStr databases from already
  installed MetaPhlAn or mOTUS databases.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_samestr_db
homepage_url: https://github.com/danielpodlesny/samestr
categories:
  - Data Managers
