name: general_matrix_tool
owner: iuc

description: Generates count and membership matrices from tabular data.

homepage_url: https://www.infrafrontier.eu/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/general_matrix_tool

long_description: |
  This tool generates two matrices from a tabular dataset.

  The first output contains the common elements shared between labels.
  The second output contains the number of shared elements.

  The user selects:
  - the column containing the labels
  - the column containing the elements to compare

  The input dataset must already be aggregated on the label column and the
  comparison column must contain comma-separated values.
  
  The generated matrices are directly compatible with the Interactive overlap
  heatmap tool, which provides an interactive visualization of the overlap
  analysis. However, this tool is completely independent and can also be used
  on its own or with other downstream analysis tools.

type: unrestricted

categories:
  - Statistics
