name: squidpy
owner: iuc
description: "Squidpy - Spatial Single Cell Analysis in Python"
homepage_url: https://squidpy.readthedocs.io
long_description: |
    Squidpy is a tool for the analysis and visualization of spatial molecular data. It builds on top of scanpy and anndata, from which it inherits modularity and scalability. It provides analysis tools that leverage the spatial coordinates of the data, as well as tissue images if available.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/squidpy
type: unrestricted
categories:
  - Single Cell
  - Spatial Omics
  - Transcriptomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the squidpy tool suite: {{ tool_name }}"
suite:
  name: "suite_squidpy"
  description: "Squidpy – Spatial Single-Cell Analysis in Python"
  long_description: |
    Squidpy is a tool for the analysis and visualization of spatial molecular data. It builds on top of scanpy and anndata, from which it inherits modularity and scalability. It provides analysis tools that leverage the spatial coordinates of the data, as well as tissue images if available.