categories: 
 - Sequence Analysis
description: Convert the AGP output from PretextView and the assembly (FASTA) into a new assembly (FASTA)
homepage_url: https://github.com/sanger-tol/agp-tpf-utils
long_description: |
  Uses fragments in the assembly (AGP) produced by PretextView to find
  matching fragments in the assembly which was fed into Pretext and output an
  assembly made from the input assembly fragments.
name: pretext_to_asm
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pretext_to_asm