categories:  # see https://toolshed.g2.bx.psu.edu/repository/browse_categories  
- Digital Humanities
description: Tool to produce a line-delimited JSON index of the contents of a WARC file.
long_description: |
  Do you have work with web archives? Web ARchive Container (WARC) files contained archived web data and their accompanying metadata.
        
  If you have a gzipped WARC and want to know what is in it, you can use warcio index. 

  warcio index accepts a WARC file and produces an index of the contents of the WARC file in line-delimited JSON.
homepage_url: https://github.com/dasch-swiss/fileidentification
name: warcio-index
owner: iuc  # tool shed username
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/warcio-index
type: unrestricted
maintainers:  # github usernames
- eamonnbell-dur