name: data_manager_perseus
owner: iuc
description: Data Manager for the Perseus taxonomy database
homepage_url: https://github.com/matnguyen/Perseus
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_perseus
long_description: |
  Downloads the NCBI taxonomy and builds the ETE3 taxonomy
  database required by Perseus.
categories:
  - Data Managers
type: unrestricted