name: rmlst_cli
owner: iuc
description: Identify bacterial species using the PubMLST rMLST API.
homepage_url: https://github.com/ssi-dk/rmlst-cli
long_description: |
  Galaxy wrapper for rmlst-cli, a command-line client for species identification
  using the PubMLST rMLST API.

  The rMLST method is described by Jolley et al. 2012,
  Microbiology 158:1005-1015. DOI: 10.1099/mic.0.055459-0
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/rmlst_cli
type: unrestricted
categories:
  - Sequence Analysis
