name: rmlst_cli
owner: iuc
description: Identify bacterial species using the PubMLST rMLST API.
homepage_url: https://github.com/ssi-dk/rmlst-cli
long_description: |
  rmlst-cli, a command-line client for species identification
  using the PubMLST rMLST API.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/rmlst_cli
type: unrestricted
categories:
  - Sequence Analysis
