categories:
- Synthetic Biology
description: De Novo Molecular Design by Reverse Engineering Fingerprints
name: molsig
owner: anthony96p
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/molecule-signature
homepage_url: https://github.com/brsynth/molecule-signature
long_description: The algorithm uses an alphabet of small molecular environments — chemical Lego bricks. It searches for combinations whose summed fingerprint exactly matches the input ECFP, formulated as a system of linear Diophantine equations. Once compatible fragment combinations are found, the method reconnects them into chemically valid molecular graphs.