categories:
- Synthetic Biology
description: De Novo Molecular Design by Reverse Engineering Fingerprints
name: molsig
owner: anthony96p
remote_repository_url: https://github.com/brsynth/molecule-signature
