name: recount3
owner: iuc
description: Retrieve harmonized RNA-seq gene expression data from recount3
long_description: |
      Galaxy wrapper for recount3.
      Downloads harmonized RNA-seq gene expression data from GTEx, TCGA,
      and other public projects using the Bioconductor recount3 package.
categories:
  - RNA-seq
  - gene expression
  - data retrieval
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/recount3
homepage_url: https://github.com/Ishikaarora13/recount3-galaxy-tool
type: unrestricted