name: mtnucratio
owner: iuc
description: Calculates Mitochondrial to Nuclear read ratio
homepage_url: https://github.com/TCLamnidis/mtnucratio
long_description: |
  This tool runs the mtnucratio utility to calculate the ratio of reads mapping to the mitochondrial genome versus the nuclear genome.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/mtnucratio
type: unrestricted
categories:
  - Sequence Analysis
