attn_dist_mode: v0
attn_positional_bias: rope
attn_positional_bias_n_spatial: 4
causal_norm: quiet_softmax
coord_dim: 2
d_model: 16
dropout: 0.0
feat_dim: 7
feat_embed_per_dim: 1
nhead: 4
num_decoder_layers: 1
num_encoder_layers: 1
pos_embed_per_dim: 4
spatial_pos_cutoff: 64
window: 3
