categories:
- Epigenetics
description: ATACseqQC bioconductor package wrappers
homepage_url: https://github.com/jianhong/ATACseqQC
name: atacseqqc
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/atacseqqc
