categories:
- Epigenetics
description: ATACseqQC bioconductor package wrappers
homepage_url: https://github.com/jianhong/ATACseqQC
name: atacseqqc
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/atacseqqc
long_description: |
  ATACseqQC package helps researchers quickly assess the quality of ATAC-seq data by easily making diagnostic plots following the published guidelines (Buenrostro et al. 2013). In addition, it has functions to preprocess ATACseq data for subsequent peak calling.
