name: heatmap
owner: iuc

description: Generate an interactive heatmap from count and membership matrices.

homepage_url: https://www.infrafrontier.eu/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/heatmap

long_description: |
  This tool generates an interactive heatmap from count and name matrices.
  Each cell represents the overlap between two entities, and hover information
  can be used to inspect the corresponding shared elements.

  The tool is generic and can be used with any compatible count/name matrices.
  It can be combined with the general_matrix_tool, but it does not depend on it and can
  be used independently.

type: unrestricted

categories:
  - Visualization
  - Statistics
