name: heatmap
owner: iuc

description: Generate an interactive heatmap from count and membership matrices.

homepage_url: https://www.infrafrontier.eu/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/heatmap

long_description: |
  This tool generates an interactive heatmap from two matrices:

  - a count matrix containing the number of shared elements
  - a membership matrix containing the corresponding element names

  The resulting heatmap can be filtered using a threshold and customized
  with user-defined axis labels and plot titles.

type: unrestricted

categories:
  - Visualization
  - Statistics
