name: taffy
owner: iuc
description: A set of tools for manipulating TAF files
long_description: |
  The Transposed Alignment Format (TAF) structures multiple sequence alignments as a 
  sequence of columns, assigning each its own line. With optional run-length encoding 
  for bases, TAF minimizes file size and solves the data fragmentation issues common 
  in block-based formats like MAF.
homepage_url: https://github.com/ComparativeGenomicsToolkit/cactus
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/taffy
categories: 
- Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for Taffy suite: {{ tool_name }}"
suite:
  name: "suite_taffy"
  description: "A set of tools for manipulating TAF files"
  long_description: |
    The Transposed Alignment Format (TAF) structures multiple sequence alignments as a 
    sequence of columns, assigning each its own line. With optional run-length encoding 
    for bases, TAF minimizes file size and solves the data fragmentation issues common 
    in block-based formats like MAF.
