name: data_manager_savont_dbs
owner: iuc
description: "Download Savont reference databases (EMU, SILVA, GreenGenes2, UNITE)"
homepage_url: "https://github.com/bluenote-1577/savont"
long_description: |
    Download and install Savont reference databases (EMU, SILVA, GreenGenes2, UNITE)
    so they can be used with the Savont classify and Savont SINTAX tools.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_savont_dbs
type: unrestricted
categories:
- Data Managers
