auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
categories:
  - Single Cell
  - Transcriptomics
homepage_url: https://bioconductor.org/packages/scuttle/
long_description: |
  scuttle provides low-level utility functions for single-cell RNA-seq analysis,
  including quality control, normalisation, and transformation, built
  around the SingleCellExperiment class.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/scuttle-1.20.0
suite:
  name: "suite_scater"
  description: 'Scuttle, Utilities for Single-Cell RNA-Seq Analysis'
type: unrestricted
