categories:
- Assembly
description:  Assess the accuracy of assembled genomic sequences
homepage_url: https://github.com/JiaoLaboratory/CRAQ
long_description:
  CRAQ (Clipping Reveals Assembly Quality) is a reference-free genome assembly evaluator that assesses the accuracy of assembled genomic sequences and provides detailed assembly quality assessment from multiple perspectives.
name: craq
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/craq
type: unrestricted