name: foldtree
owner: iuc
description: Infer a phylogenetic tree from protein structures.
homepage_url: https://github.com/DessimozLab/fold_tree
long_description: |
    Foldtree creates phylogenetic trees from protein structures by using Foldseek to align protein structures and generate distance matrices for tree construction.
    See https://www.nature.com/articles/s41594-025-01649-8.

remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/foldtree
categories:
    - "Phylogenetics"
