name: cpc2
owner: iuc
description: Coding Potential Calculator 2 (CPC2)
long_description: |
  CPC2 is a fast, alignment-free coding potential calculator that predicts whether an RNA transcript is protein-coding or non-coding, based on sequence intrinsic features (ORF length/integrity, Fickett score, and peptide isoelectric point).
homepage_url: http://cpc2.gao-lab.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/cpc2
type: unrestricted
categories:
  - RNA
  - Sequence Analysis