name: Faffy
owner: iuc
description: A set of Paffy suite utilities for manipulating FASTA files
long_description: |
  Faffy is a utility within the Paffy suite for manipulating FASTA files, providing tools to chunk files, merge multiple sequences, and extract specific subsequences.
homepage_url: https://github.com/ComparativeGenomicsToolkit/cactus
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/paffy
categories: 
- Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the Paffy suite utility Faffy: {{ tool_name }}"
suite:
  name: "suite_faffy"
  description: "A set of Paffy suite utilities for manipulating FASTA files"
  long_description: |
    Faffy is a utility within the Paffy suite for manipulating FASTA files, providing tools to chunk files, merge multiple sequences, and extract specific subsequences.
