categories:
- Text Manipulation
description: jq is a lightweight and flexible command-line JSON processor
homepage_url: https://jqlang.org/
long_description: |
  jq is like sed for JSON data. It can slice, filter, map, and transform
  structured data from JSON or plain-text inputs and can emit JSON, text, or
  tabular output for downstream Galaxy tools.
name: jq
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/jq
type: unrestricted
