auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
categories:
  - Single Cell
  - Transcriptomics
homepage_url: https://bioconductor.org/packages/SingleCellExperiment/
long_description: |
  SingleCellExperiment provides a container for single-cell genomics data,
  built around the SummarizedExperiment class with extensions for reduced
  dimensions and alternative experiments.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/singlecellexperiment-1.32.0
suite:
  name: "suite_singlecellexperiment"
  description: 'SingleCellExperiment, S4 Classes for Single Cell Data'
type: unrestricted
