categories:
  - Transcriptomics
  - Single-cell
description: Galaxy wrappers for the Bioconductor SingleCellExperiment package
long_description: |
  SingleCellExperiment provides a container for single-cell genomics data,
  built around the SummarizedExperiment class with extensions for reduced
  dimensions and alternative experiments.
name: singlecellexperiment
owner: iuc
