name: data_manager_pmlst_ssi_database
owner: iuc
description: Install or update the pMLST-SSI database for Galaxy.
long_description: |
  Data manager for installing and updating the pMLST database used by the
  pMLST-SSI Galaxy tool wrapper.
categories:
  - Data Managers
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_pmlst_ssi_database
homepage_url: https://github.com/ssi-dk/pmlst
type: unrestricted
