owner: iuc
name: scop3p
description: "Fetch post-translational modifications (PTMs) from Scop3P database"
type: unrestricted
categories:
  - Proteomics
  - Data Source
long_description: |
  Scop3P provides a unique and powerful resource to explore
  and understand the impact of phospho-sites on protein
  structure and function, and can thus serve as a springboard 
  for researchers seeking to analyse and, interpret a given 
  phospho-site or phosphoprotein in a structural, biophysical, 
  and biological context.  
remote_repository_url: https://github.com/Bio2Byte/scop3p-api-client
homepage_url: https://iomics.ugent.be/scop3p/index
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}"
