name: ucsc_hubcheck
owner: iuc
description: hubCheck validates a UCSC track hub
long_description: hubCheck validates a UCSC track hub
homepage_url: https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/ucsc_tools/hubcheck
type: unrestricted
categories:
  - Visualization
