name: metacoag
owner: iuc
type: unrestricted
categories:
- Metagenomics
description: metagenomic contig binning tool
long_description: |
  MetaCoAG is a metagenomic contig binning tool that makes 
  use of the connectivity information found in assembly graphs, 
  apart from the composition and coverage information. 
  MetaCoAG makes use of single-copy marker genes along with a graph 
  matching technique and a label propagation technique to bin contigs.
homepage_url: https://github.com/metagentools/MetaCoAG
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/metacoag
