categories:
  - Sequence Analysis
  - Variant Analysis
description: Build a pangenome variation graph (wfmash + seqwish + smoothxg + gfaffix + odgi)
homepage_url: https://github.com/pangenome/pggb
long_description: |
  The PanGenome Graph Builder (PGGB) constructs pangenome variation graphs from a set of input sequences.
  It uses all-to-all alignments (wfmash), graph induction (seqwish), POA smoothing (smoothxg),
  affix collapse (gfaffix), and visualization/statistics (odgi).
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pggb
type: unrestricted
