name: pmlst_ssi
owner: povilasmat
description: pMLST bacterial plasmid typing tool.
long_description: |
  pMLST-SSI identifies plasmid MLST profiles from assembled genomes or reads
  using the pMLST database from the Center for Genomic Epidemiology.
categories:
  - Sequence Analysis
remote_repository_url: https://github.com/ssi-dk/pmlst
homepage_url: https://github.com/ssi-dk/pmlst
type: unrestricted
