categories:
  - Data Managers
description: Data manager for downloading gapseq references sequences and populating the data table
homepage_url: https://github.com/jotech/gapseq
long_description: |
  This data manager downloads reference sequences for the tool gapseq according to the 'gapseq update-sequences' command and then populates the gapseq_databases data table.
name: data_manager_gapseq_update_sequences
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_gapseq_update_sequences
type: unrestricted

