categories:
- Next Gen Mappers
description: minibwa is a fast successor to BWA-MEM for short and accurate long reads.
long_description: |
  minibwa aligns short reads and accurate long reads to a reference genome. It
  combines the variable-length seeding of BWA-MEM with the chaining and base-level
  alignment of minimap2, and additionally supports Hi-C reads and directional
  bisulfite sequencing reads.
name: minibwa
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/minibwa
homepage_url: https://github.com/lh3/minibwa
type: unrestricted
