name: neighbors
owner: iuc
description: Identify target and neighbor genomes for marker discovery
long_description: Identify target and neighbor genomes for marker discovery
homepage_url: https://github.com/EvolBioInf/neighbors
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/neighbors
type: unrestricted
categories:
  - Phylogenetics
  - Sequence Analysis
