name: ucsc_genepredtobed
owner: iuc
description: genePredToBed converts a genePred gene model to BED12
long_description: genePredToBed converts a genePred gene model to BED12
homepage_url: https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/ucsc_tools/genepredtobed
type: unrestricted
categories:
  - Convert Formats
