name: pgxrpi
owner: iuc
description: pgxLoader and pgxFreqplot functions from pgxRpi
homepage_url: https://github.com/progenetix/pgxRpi
long_description: |
    pgxRpi is an R wrapper package for the Progenetix REST API that leverages the capabilities of the Beacon v2 specification. It also provides functions to enhance the visualisation of the retrieved genomic variation data.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pgxRpi
suite:
  name: suite_pgxrpi
  description: pgxLoader and pgxFreqplot functions from pgxRpi
  long_description: A suite of Galaxy wrappers for pgxrpi tools.
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}."
type: unrestricted
categories:
- Variant Analysis
