name: pgxrpi
owner: iuc
description: pgxLoader and pgxFreqplot functions from pgxRpi
homepage_url: https://github.com/progenetix/pgxRpi
long_description: |
    pgxRpi is an R wrapper package for the Progenetix REST API that leverages the capabilities of the Beacon v2 specification. It also provides functions to enhance the visualisation of the retrieved genomic variation data.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pgxRpi
type: unrestricted
categories:
- Variant Analysis

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "pgxRpi: {{ tool_name }}"

suite:
  name: "pgxrpi_suite"
  description: "A suite of Galaxy tools for accessing and visualizing Progenetix genomic variation data via the Beacon v2 API"
  
  long_description: |
    pgxRpi is an R wrapper package for the Progenetix REST API that leverages the capabilities of the Beacon v2 specification. It also provides functions to enhance the visualisation of the retrieved genomic variation data.
    
    This suite includes:
    - **pgx_loader**: Load various data from Progenetix database via the Beacon v2 API
    - **pgx_freqplot**: Plot the frequency of copy number variation in specific cohorts
