name: clinker
owner: iuc
description: Interactive gene cluster comparison figures
long_description: |
  clinker compares annotated gene clusters and plasmids and creates a
  standalone interactive HTML visualization.
homepage_url: https://github.com/gamcil/clinker
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/clinker
type: unrestricted
categories:
  - Sequence Analysis
  - Visualization
