name: sexdeterrmine
owner: iuc
description: Sex.DetERRmine calculates the relative coverage of sex chromosomes to determine biological sex.
homepage_url: https://github.com/TCLamnidis/Sex.DetERRmine
long_description: |
  Sex.DetERRmine is designed for sex determination from low-depth sequencing data, 
  making it particularly useful for ancient DNA (aDNA) analysis. It calculates Rx and Ry 
  metrics based on the relative coverage of X and Y chromosomes compared to autosomes.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/sexdeterrmine
type: unrestricted
categories:
  - Sequence Analysis
  - Statistics