name: wgcna
owner: iuc
description: Weighted Gene Co-expression Network Analysis 
long_description: |
      Galaxy wrapper for WGCNA.
      Performs Weighted Gene Co-expression Network Analysis on gene expression data.
      WGCNA is a systems biology method for describing the correlation patterns among genes. 
      It can be used to identify modules of highly correlated genes, summarize such modules using the module eigengene or 
      an intramodular hub gene, relate modules to one another and to external sample traits (using eigengene network methodology), 
      and calculate module membership measures.
categories:
  - Transcriptomics
  - Statistics
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/wgcna
homepage_url: https://github.com/LieberInstitute/wgcna
type: unrestricted
