---
categories: [Genome annotation]
description: Tiberius is a tool for deep learning-based ab initio gene structure prediction
homepage_url: https://github.com/Gaius-Augustus/Tiberius
long_description: Tiberius is a tool for deep learning-based ab initio gene structure prediction
name: tiberius
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/tiberius
type: unrestricted
