name: vardictcpp
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/vardictcpp
homepage_url: "https://github.com/joachimwolff/vardictcpp"
description: "VarDict (C++) - calls SNVs and indels from a single BAM (C++ port of VarDict)"
categories:
- "Variant Analysis"
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}"
