name: angsd
owner: iuc
description: ANGSD and nuclear contamination estimation tools for ancient DNA analysis.
homepage_url: https://github.com/angsd/angsd
long_description: |
  This repository contains ANGSD for generating internal counts and an X-chromosome 
  contamination estimation tool, ported from the nf-core/eager pipeline. 
  It is designed for paleogenomics research to assess sample quality.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/angsd
type: unrestricted
categories:
  - Sequence Analysis
  - Statistics