name: angsd
owner: iuc
description: ANGSD tools for calculating various genomic statistics, contamination, and error estimation from BAM files.
homepage_url: https://github.com/angsd/angsd
long_description: |
  This repository contains ANGSD tools for generating summary statistics from BAM files. 
  It includes modules for X-chromosome nuclear contamination estimation, sequencing error estimation, allele counting, depth distributions, and mismatch matrix calculations.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/angsd
type: unrestricted
categories:
  - Sequence Analysis
  - Statistics