name: proseg
owner: iuc
description: Probabilistic cell segmentation for spatial transcriptomics
homepage_url: https://github.com/vpetukhov/proseg
long_description: |
  Proseg is a tool for cell segmentation of spatial transcriptomics data.
  It uses a probabilistic model to assign transcripts to cells, providing robust
  segmentation even in noisy datasets.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/proseg
type: unrestricted
categories:
  - Transcriptomics
