# Index format
main-version = 3
minor-version = 4
# LexicHash
max-K = 31
masks = 20000
rand-seed = 1
# Seed distance
max-seed-dist = 100
seed-dist-in-desert = 50
# Seeds (k-mer-value data) files
chunks = 4
index-partitions = 4096
# Input genomes
input-genomes = 1
# Input bases
input-bases = 7417
# Genome data. 
# 'genomes' might be larger than 'input-genomes', as some big fragmented genomes are split into multiple chunks.
# In this case, 'genome-batch-size' is not accurate, being variable in different batches.
genomes = 1
genome-batch-size = 1
genome-batches = 1
contig-interval = 1000
# Lowercase bases in soft-masked low-complexity regions are treated as A's and are not seeded,
# while they are saved for base-level alignment.
soft-masking = false
# If a mask captures the same k-mer at more than N positions of a genome,
# only the first N positions are retained. (0 for no filtering)
max-kmer-freq = 10
