name: magmax
owner: iuc
description: bin Merging and reAssembly tool
homepage_url: https://github.com/soedinglab/MAGmax
long_description: |
  MAGmax is a dereplication tool designed to maximize the recovery of
  Metagenome-Assembled Genomes (MAGs) through bin Merging and reAssembly.
  It performs dereplication in three stages: (i) grouping bins based on
  average sequence identity, (ii) merging bins within each group,
  and (iii) reassembling the merged bins.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/magmax
type: unrestricted
categories: 
- Metagenomics
