name: kneaddata
owner: iuc
type: unrestricted
description: Quality control and contaminant removal for metagenomic data
homepage_url: https://github.com/biobakery/kneaddata
categories:
  - Sequence Analysis
  - Metagenomics
  - Quality Control
