categories:
  - Sequence Analysis
  - Variant Analysis
description: POA-aware graph smoother for pangenome graphs
homepage_url: https://github.com/pangenome/smoothxg
long_description: |
  smoothxg finds blocks of paths that are collinear within a variation graph.
  It applies partial order alignment to each block, yielding an acyclic variation graph.
  Then, to yield a "smoothed" graph, it walks the original paths to lace these subgraphs together.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/smoothxg
type: unrestricted
