#!/usr/bin/env python3

from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
from pathlib import Path

ham = 'docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1'

test_data_url = (
    'https://zenodo.org/record/5908204/files/'
    'zymoD6331std-ecoli-ten-percent.fq.gz')

HTTP = HTTPRemoteProvider()
test_input = HTTP.remote(
    test_data_url,
    keep_local=True)


rule target:
    input:
        expand('output/{redundancy}/asm',
               redundancy=['high', 'normal'])


rule hifiasm_meta:
    input:
        'data/zymoD6331std-ecoli-ten-percent.fq.gz'
    output:
        od = directory('output/{redundancy}/asm')
    params:
        force = lambda wildcards:
            '--force-rs' if wildcards.redundancy == 'high' else ''
    threads:
        workflow.cores
    log:
        'output/logs/hifiasm_meta.{redundancy}.log'
    benchmark:
        'output/benchmarks/hifiasm_meta.{redundancy}.log'
    container:
        ham
    shell:
        'hifiasm_meta '
        '-t {threads} '
        '{params.force} '
        '-o {output.od} '
        '2> {log}'


rule get_input:
    input:
        test_input
    output:
        'data/zymoD6331std-ecoli-ten-percent.fq.gz'
    shell:
        'cp {input} {output}'
