name: ssiamb
description: ambiguous SNV counter from reads mapped back to their assembly.
long_description: |
  ssiamb counts ambiguous SNV sites from trimmed paired-end reads mapped back to
  their own supplied assembly.
homepage_url: https://github.com/ssi-dk/ssiamb
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/ssiamb
owner: iuc
type: unrestricted
categories:
  - Variant Analysis

