categories:
- Transcriptomics
- Single Cell
- Statistics
- Cell Biology
description: Single-cell-informed cell-type deconvolution of bulk and spatial transcriptomic data
long_description: |
  Rectangle is a Python package for single-cell-informed cell-type deconvolution
  of bulk and spatial transcriptomic data. It creates signatures from single-cell
  data and deconvolutes bulk data to estimate cell-type fractions.
name: rectanglepy
owner: iuc
homepage_url: https://github.com/ByrumLab/rectanglepy
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/rectanglepy
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for Rectangle: {{ tool_name }}."
suite:
  name: "suite_rectanglepy"
  description: "A suite of Galaxy tools for Rectangle."
  type: repository_suite_definition
