categories:
- Transcriptomics
- Single Cell
- Spatial Omics
- Statistics
description: Single-cell-informed cell-type deconvolution of bulk and spatial transcriptomic data
long_description: |
  Rectangle is a Python package for single-cell-informed cell-type deconvolution
  of bulk and spatial transcriptomic data. It creates signatures from single-cell
  data and deconvolutes bulk data to estimate cell-type fractions.
name: rectanglepy
owner: iuc
homepage_url: https://github.com/ComputationalBiomedicineGroup/Rectangle
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/rectanglepy
type: unrestricted
