categories:
- Machine Learning
description: A FAIR Machine Learning Framework for Benchmarking, Feature Selection, and Hyperparameter Optimization of Machine Learning Models for Multiomics Data in Galaxy
homepage_url: https://github.com/usegalaxy-eu/MultiOmicsClassification
long_description: |
 The MultiClassPrediction tool  is designed for multi-omics data analysis within the Galaxy platform,   enabling reproducible and standardized model evaluation across diverse biological datasets.
name: multiclassprediction
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/multi-omics-classification
type: unrestricted
