name: data_manager_trackastra_models
owner: iuc
description: Install pretrained and administrator-supplied Trackastra models
homepage_url: https://github.com/weigertlab/trackastra
long_description: |
  Data manager for installing Trackastra model directories in a Galaxy tool-data table.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_trackastra_models
categories:
  - Data Managers
