
optional_samples_cols_mapping = {
    "collection date": "collection_date",
    "geographic location (latitude)": "geographic_location_latitude",
    "geographic location (longitude)": "geographic_location_longitude",
    "geographic location (region)": "geographic_location_region",
    "sample capture status": "sample_capture_status",
    "host disease outcome": "host_disease_outcome",
    "host_age": "host_age",
    "virus identifier": "virus_identifier",
    "receipt date": "receipt_date",
    "definition for seropositive sample": "definition_for_seropositive_sample",
    "serotype (required for a seropositive sample)": "serotype",
    "host habitat": "host_habitat",
    "isolation source host-associated": "isolation_source_host_associated",
    "host behaviour": "host_behaviour",
    "isolation source non-host-associated": "isolation_source_non_host_associated",
    "subject exposure": "subject_exposure",
    "subject exposure duration": "subject_exposure_duration",
    "type exposure": "type_exposure",
    "personal protective equipment": "personal_protective_equipment",
    "hospitalisation": "hospitalisation",
    "illness duration": "illness_duration",
    "illness symptoms": "illness_symptoms",
    "sample storage conditions": "sample_storage_conditions",
    "strain": "strain",
    "host description": "host_description",
    "gravidity": "gravidity"
}
