#!/usr/bin/env python3

import json
import sys

# first argument is script name; second should be mmvcOutput path; third should be name for fasta header; the fourth argument should be the path to save the fasta at
mmvcOutput = sys.argv[1]
fastaHeaderName = sys.argv[2]
fastaFilePath = sys.argv[3]

with open(mmvcOutput) as f:
    data = json.load(f)
consensus = data["consensus"]
consensusFasta = ">" + fastaHeaderName + "\n" + consensus + "\n"
f = open(fastaFilePath, "w")
f.write(consensusFasta)
