name: sopa
owner: iuc
description: "sopa – Spatial-omics pipeline and analysis"
homepage_url: https://prism-oncology.github.io/sopa/
long_description: |
    Built on top of SpatialData, Sopa enables processing and analyses of spatial omics data with single-cell resolution (spatial transcriptomics or multiplex imaging data) using a standard data structure and output. We currently support the following technologies: Xenium, Visium HD, MERSCOPE, CosMx, PhenoCycler, MACSima, Molecular Cartography, and others. Sopa was designed for generability and low memory consumption on large images (scales to 1TB+ images).
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/sopa
type: unrestricted
categories:
  - Single Cell
  - Spatial Omics
  - Transcriptomics
  - Proteomics
  - Imaging
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the sopa tool suite: {{ tool_name }}"
suite:
  name: "suite_sopa"
  description: "sopa – Spatial-omics pipeline and analysis"
  long_description: |
    Built on top of SpatialData, Sopa enables processing and analyses of spatial omics data with single-cell resolution (spatial transcriptomics or multiplex imaging data) using a standard data structure and output. We currently support the following technologies: Xenium, Visium HD, MERSCOPE, CosMx, PhenoCycler, MACSima, Molecular Cartography, and others. Sopa was designed for generability and low memory consumption on large images (scales to 1TB+ images).