name: genebed_maf_to_fasta
owner: iuc
description: Stitch gene blocks given a set of coding exon intervals
long_description: Stitch gene blocks given a set of coding exon intervals from a multiple alignment format (MAF) file to produce FASTA sequences.
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/genebed_maf_to_fasta/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/genebed_maf_to_fasta
categories:
  - Genomic Interval Operations
