name: hicap
owner: iuc
description: Identify cap locus serotype and structure in Haemophilus influenzae assemblies
long_description: Identify cap locus serotype and structure in Haemophilus influenzae assemblies
homepage_url: https://github.com/scwatts/hicap
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/hicap
type: unrestricted
categories:
  - Sequence Analysis
